'use strict';

const glfw = require('../core');


const emptyFunction = () => undefined;

const keyNames = {
	[glfw.KEY_BACKSPACE]     : 'Backspace',
	[glfw.KEY_CAPS_LOCK]     : 'CapsLock',
	[glfw.KEY_DELETE]        : 'Delete',
	[glfw.KEY_END]           : 'End',
	[glfw.KEY_ENTER]         : 'Enter',
	[glfw.KEY_ESCAPE]        : 'Escape',
	[glfw.KEY_F1]            : 'F1',
	[glfw.KEY_F2]            : 'F2',
	[glfw.KEY_F3]            : 'F3',
	[glfw.KEY_F4]            : 'F4',
	[glfw.KEY_F5]            : 'F5',
	[glfw.KEY_F6]            : 'F6',
	[glfw.KEY_F7]            : 'F7',
	[glfw.KEY_F8]            : 'F8',
	[glfw.KEY_F9]            : 'F9',
	[glfw.KEY_F10]           : 'F10',
	[glfw.KEY_F11]           : 'F11',
	[glfw.KEY_F12]           : 'F12',
	[glfw.KEY_F13]           : 'F13',
	[glfw.KEY_F14]           : 'F14',
	[glfw.KEY_F15]           : 'F15',
	[glfw.KEY_F16]           : 'F16',
	[glfw.KEY_F17]           : 'F17',
	[glfw.KEY_F18]           : 'F18',
	[glfw.KEY_F19]           : 'F19',
	[glfw.KEY_F20]           : 'F20',
	[glfw.KEY_F21]           : 'F21',
	[glfw.KEY_F22]           : 'F22',
	[glfw.KEY_F23]           : 'F23',
	[glfw.KEY_F24]           : 'F24',
	[glfw.KEY_F25]           : 'F25',
	[glfw.KEY_HOME]          : 'Home',
	[glfw.KEY_INSERT]        : 'Insert',
	[glfw.KEY_KP_ENTER]      : 'Enter',
	[glfw.KEY_KP_DECIMAL]    : 'Delete',
	[glfw.KEY_KP_EQUAL]      : 'Equal',
	[glfw.KEY_LEFT]          : 'ArrowLeft',
	[glfw.KEY_UP]            : 'ArrowUp',
	[glfw.KEY_RIGHT]         : 'ArrowRight',
	[glfw.KEY_DOWN]          : 'ArrowDown',
	[glfw.KEY_LEFT_ALT]      : 'Alt',
	[glfw.KEY_RIGHT_ALT]     : 'Alt',
	[glfw.KEY_LEFT_BRACKET]  : 'LeftBracket',
	[glfw.KEY_RIGHT_BRACKET] : 'RightBracket',
	[glfw.KEY_LEFT_CONTROL]  : 'Control',
	[glfw.KEY_RIGHT_CONTROL] : 'Control',
	[glfw.KEY_LEFT_SHIFT]    : 'Shift',
	[glfw.KEY_RIGHT_SHIFT]   : 'Shift',
	[glfw.KEY_LEFT_SUPER]    : 'Meta',
	[glfw.KEY_RIGHT_SUPER]   : 'Meta',
	[glfw.KEY_MENU]          : 'ContextMenu',
	[glfw.KEY_NUM_LOCK]      : 'NumLock',
	[glfw.KEY_PAGE_UP]       : 'PageUp',
	[glfw.KEY_PAGE_DOWN]     : 'PageDown',
	[glfw.KEY_PAUSE]         : 'Pause',
	[glfw.KEY_PRINT_SCREEN]  : 'PrintScreen',
	[glfw.KEY_SCROLL_LOCK]   : 'ScrollLock',
	[glfw.KEY_SPACE]         : ' ',
	[glfw.KEY_TAB]           : 'Tab',
};

const codeNames = {
	...keyNames,
	[glfw.KEY_EQUAL]         : 'Equal',
	[glfw.KEY_COMMA]         : 'Comma',
	[glfw.KEY_MINUS]         : 'Minus',
	[glfw.KEY_PERIOD]        : 'Period',
	[glfw.KEY_SEMICOLON]     : 'Semicolon',
	[glfw.KEY_SLASH]         : 'Slash',
	[glfw.KEY_APOSTROPHE]    : 'Apostrophe',
	[glfw.KEY_BACKSLASH]     : 'Backslash',
	[glfw.KEY_SPACE]         : 'Space',
	[glfw.KEY_GRAVE_ACCENT]  : 'Backquote',
	[glfw.KEY_LEFT_ALT]      : 'AltLeft',
	[glfw.KEY_RIGHT_ALT]     : 'AltRight',
	[glfw.KEY_LEFT_CONTROL]  : 'ControlLeft',
	[glfw.KEY_RIGHT_CONTROL] : 'ControlRight',
	[glfw.KEY_LEFT_SHIFT]    : 'ShiftLeft',
	[glfw.KEY_RIGHT_SHIFT]   : 'ShiftRight',
	[glfw.KEY_LEFT_SUPER]    : 'MetaLeft',
	[glfw.KEY_RIGHT_SUPER]   : 'MetaRight',
	[glfw.KEY_LEFT]          : 'ArrowLeft',
	[glfw.KEY_UP]            : 'ArrowUp',
	[glfw.KEY_RIGHT]         : 'ArrowRight',
	[glfw.KEY_DOWN]          : 'ArrowDown',
	[glfw.KEY_0]             : 'Digit0',
	[glfw.KEY_1]             : 'Digit1',
	[glfw.KEY_2]             : 'Digit2',
	[glfw.KEY_3]             : 'Digit3',
	[glfw.KEY_4]             : 'Digit4',
	[glfw.KEY_5]             : 'Digit5',
	[glfw.KEY_6]             : 'Digit6',
	[glfw.KEY_7]             : 'Digit7',
	[glfw.KEY_8]             : 'Digit8',
	[glfw.KEY_9]             : 'Digit9',
	[glfw.KEY_KP_0]          : 'Numpad0',
	[glfw.KEY_KP_1]          : 'Numpad1',
	[glfw.KEY_KP_2]          : 'Numpad2',
	[glfw.KEY_KP_3]          : 'Numpad3',
	[glfw.KEY_KP_4]          : 'Numpad4',
	[glfw.KEY_KP_5]          : 'Numpad5',
	[glfw.KEY_KP_6]          : 'Numpad6',
	[glfw.KEY_KP_7]          : 'Numpad7',
	[glfw.KEY_KP_8]          : 'Numpad8',
	[glfw.KEY_KP_9]          : 'Numpad9',
	[glfw.KEY_KP_ADD]        : 'NumpadAdd',
	[glfw.KEY_KP_DECIMAL]    : 'NumpadDecimal',
	[glfw.KEY_KP_DIVIDE]     : 'NumpadDivide',
	[glfw.KEY_KP_ENTER]      : 'NumpadEnter',
	[glfw.KEY_KP_EQUAL]      : 'Equal',
	[glfw.KEY_KP_MULTIPLY]   : 'NumpadMultiply',
	[glfw.KEY_KP_SUBTRACT]   : 'NumpadSubtract',
};


const extraCodes = {
	[glfw.KEY_APOSTROPHE]    : 222,
	[glfw.KEY_BACKSLASH]     : 220,
	[glfw.KEY_BACKSPACE]     : 8,
	[glfw.KEY_CAPS_LOCK]     : 20,
	[glfw.KEY_COMMA]         : 188,
	[glfw.KEY_DELETE]        : 46,
	[glfw.KEY_DOWN]          : 40,
	[glfw.KEY_END]           : 35,
	[glfw.KEY_ENTER]         : 13,
	[glfw.KEY_EQUAL]         : 187,
	[glfw.KEY_ESCAPE]        : 27,
	[glfw.KEY_F10]           : 121,
	[glfw.KEY_F11]           : 122,
	[glfw.KEY_F12]           : 123,
	[glfw.KEY_F13]           : 123,
	[glfw.KEY_F14]           : 123,
	[glfw.KEY_F15]           : 123,
	[glfw.KEY_F16]           : 123,
	[glfw.KEY_F17]           : 123,
	[glfw.KEY_F18]           : 123,
	[glfw.KEY_F19]           : 123,
	[glfw.KEY_F1]            : 112,
	[glfw.KEY_F20]           : 123,
	[glfw.KEY_F21]           : 123,
	[glfw.KEY_F22]           : 123,
	[glfw.KEY_F23]           : 123,
	[glfw.KEY_F24]           : 123,
	[glfw.KEY_F25]           : 123,
	[glfw.KEY_F2]            : 113,
	[glfw.KEY_F3]            : 114,
	[glfw.KEY_F4]            : 115,
	[glfw.KEY_F5]            : 116,
	[glfw.KEY_F6]            : 117,
	[glfw.KEY_F7]            : 118,
	[glfw.KEY_F8]            : 119,
	[glfw.KEY_F9]            : 120,
	[glfw.KEY_GRAVE_ACCENT]  : 192,
	[glfw.KEY_HOME]          : 36,
	[glfw.KEY_INSERT]        : 45,
	[glfw.KEY_KP_0]          : 96,
	[glfw.KEY_KP_1]          : 97,
	[glfw.KEY_KP_2]          : 98,
	[glfw.KEY_KP_3]          : 99,
	[glfw.KEY_KP_4]          : 100,
	[glfw.KEY_KP_5]          : 101,
	[glfw.KEY_KP_6]          : 102,
	[glfw.KEY_KP_7]          : 103,
	[glfw.KEY_KP_8]          : 104,
	[glfw.KEY_KP_9]          : 105,
	[glfw.KEY_KP_ADD]        : 107,
	[glfw.KEY_KP_DECIMAL]    : 110,
	[glfw.KEY_KP_DIVIDE]     : 111,
	[glfw.KEY_KP_ENTER]      : 13,
	[glfw.KEY_KP_EQUAL]      : 187,
	[glfw.KEY_KP_MULTIPLY]   : 106,
	[glfw.KEY_KP_SUBTRACT]   : 109,
	[glfw.KEY_LEFT]          : 37,
	[glfw.KEY_LEFT_ALT]      : 18,
	[glfw.KEY_LEFT_BRACKET]  : 219,
	[glfw.KEY_LEFT_CONTROL]  : 17,
	[glfw.KEY_LEFT_SHIFT]    : 16,
	[glfw.KEY_LEFT_SUPER]    : 91,
	[glfw.KEY_MENU]          : 18,
	[glfw.KEY_MINUS]         : 189,
	[glfw.KEY_NUM_LOCK]      : 144,
	[glfw.KEY_PAGE_DOWN]     : 34,
	[glfw.KEY_PAGE_UP]       : 33,
	[glfw.KEY_PAUSE]         : 19,
	[glfw.KEY_PERIOD]        : 190,
	[glfw.KEY_PRINT_SCREEN]  : 144,
	[glfw.KEY_RIGHT]         : 39,
	[glfw.KEY_RIGHT_ALT]     : 18,
	[glfw.KEY_RIGHT_BRACKET] : 221,
	[glfw.KEY_RIGHT_CONTROL] : 17,
	[glfw.KEY_RIGHT_SHIFT]   : 16,
	[glfw.KEY_RIGHT_SUPER]   : 93,
	[glfw.KEY_SCROLL_LOCK]   : 145,
	[glfw.KEY_SEMICOLON]     : 186,
	[glfw.KEY_SLASH]         : 191,
	[glfw.KEY_SPACE]         : 32,
	[glfw.KEY_TAB]           : 9,
	[glfw.KEY_UP]            : 38,
};


const ESC_KEY = 27;

const F_KEY = 70;


module.exports = {
	emptyFunction,
	keyNames,
	codeNames,
	extraCodes,
	ESC_KEY,
	F_KEY,
};
